### ISSUE TITLE
Unable to plot with enrichMap

### ISSUE THREAD

**Issue by llrs** [GuangchuangYu/DOSE#15]
I am trying to plot something following the vignette of DOSE package but I keep getting the same error:

```r
enrichMap(reactome_enrich)
Error in symbols(x = coords[, 1], y = coords[, 2], bg = vertex.color,  : 
  invalid symbol coordinates
Calls: enrichMap -> netplot -> plot.igraph -> <Anonymous> -> symbols
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
```

It doesn't matter the layout I select, the error persist, I tried looking down to the plot.igraph function, but I am unable to find where the specific line of symbols(x = coords[, 1], y = coords[, 2], bg = vertex.color, is called.

What I want to plot is:

```r
dput(summary(reactome_enrich))
structure(list(ID = "392170", Description = "ADP signalling through P2Y purinoceptor 12", 
    GeneRatio = structure(2L, .Label = c("1/19", "2/19", "3/19", 
    "4/19", "5/19", "7/19"), class = "factor"), BgRatio = structure(78L, .Label = c("102/6400", 
    "10/6400", "106/6400", "107/6400", "109/6400", "111/6400", 
    "113/6400", "114/6400", "11/6400", "116/6400", "118/6400", 
    "123/6400", "12/6400", "13/6400", "136/6400", "143/6400", 
    "1449/6400", "14/6400", "150/6400", "153/6400", "15/6400", 
    "161/6400", "162/6400", "16/6400", "17/6400", "1764/6400", 
    "182/6400", "184/6400", "189/6400", "193/6400", "19/6400", 
    "231/6400", "23/6400", "24/6400", "246/6400", "250/6400", 
    "272/6400", "27/6400", "282/6400", "28/6400", "29/6400", 
    "299/6400", "344/6400", "35/6400", "3/6400", "36/6400", "376/6400", 
    "39/6400", "40/6400", "407/6400", "42/6400", "427/6400", 
    "436/6400", "44/6400", "446/6400", "45/6400", "46/6400", 
    "493/6400", "49/6400", "503/6400", "519/6400", "54/6400", 
    "55/6400", "557/6400", "5/6400", "565/6400", "57/6400", "60/6400", 
    "63/6400", "637/6400", "640/6400", "64/6400", "661/6400", 
    "6/6400", "69/6400", "71/6400", "74/6400", "7/6400", "76/6400", 
    "80/6400", "81/6400", "82/6400", "843/6400", "84/6400", "8/6400", 
    "86/6400", "87/6400", "89/6400", "90/6400", "92/6400", "935/6400", 
    "93/6400", "9/6400", "96/6400", "99/6400"), class = "factor"), 
    pvalue = 0.000173821781250736, p.adjust = 0.0229444751250971, 
    qvalue = 0.0186629701974474, geneID = "GNAI3/P2RY12", Count = 2L), .Names = c("ID", 
"Description", "GeneRatio", "BgRatio", "pvalue", "p.adjust", 
"qvalue", "geneID", "Count"), row.names = "392170", class = "data.frame")
```

**Comment by GuangchuangYu** [comment]
your result only have one term enriched. This is why `enrichMap` fail. `enrichMap` is designed to summarize result that have many/several enriched terms.

**Comment by llrs** [comment]
But it shouldn't fail if there is only one, should it? I would expect just one dot, or even a better informative error.

**Comment by GuangchuangYu** [comment]
done. It will plot one dot in future

**Comment by llrs** [comment]
I downloaded and installed version 2.10 and I still can't plot it. The error now is:

```r
 enrichMap(reactome_enrich)
Error in y$pvalue : $ operator is invalid for atomic vectors
```
The error seems to come from this commit 52d19e7da. Did it work correctly for you? Thanks

**Comment by GuangchuangYu** [comment]
your `reactome_enrich` has 0 row?

**Comment by llrs** [comment]
It is the same I posted previously

**Comment by GuangchuangYu** [comment]
then it should be plotted.

re-install github version and try again.
